### ISSUE TITLE
_grokparsefailure

### ISSUE THREAD

**Issue by mesutgungor** [ITLinuxCL/zimbra_logstash#8]
I have tested and debug the patterns working very well bu i see _grokparsefailure error in the kibana interface. for example the following log in the debugger.

http://grokdebug.herokuapp.com/
![grok debugger](https://cloud.githubusercontent.com/assets/4573148/24293992/81409a96-10a5-11e7-9248-5b937839d815.png)

45A69242749: to=<clietech@gmail.com>, relay=127.0.0.1[127.0.0.1]:10026, delay=57, delays=0.95/0.01/26/29, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10030): 250 2.0.0 Ok: queued as 6F16724274A)

i got the following result which is fine 

{
  "qid": [
    "45A69242749"
  ],
  "to": [
    "clietech@gmail.com"
  ],
  "to_domain": [
    "gmail.com",
    null
  ],
  "orig_to": [
    null
  ],
  "dst_relayhost": [
    "127.0.0.1"
  ],
  "dst_relayip": [
    "127.0.0.1"
  ],
  "conn_use": [
    null
  ],
  "delay": [
    "57"
  ],
  "delays": [
    "0.95/0.01/26/29"
  ],
  "dsn": [
    "2.0.0"
  ],
  "result": [
    "sent"
  ],
  "result_comment": [
    null
  ],
  "reason": [
    "250 2.0.0 from MTA(smtp:[127.0.0.1]:10030): 250 2.0.0 Ok: queued as 6F16724274A"
  ]
}
but in my server ELK the filter tags the message _grokparsefailure, unknown

what can cause the problem.  i am using 10-postfix-filter.conf

**Comment by pbruna** [comment]
Hello,
The `unknown` is added for debugging purpose, nothing to worry about.
`_grokparsefailure` is added because the code has several patterns and not all the log messages match, so is not ideal, but it's safe.

When I have the time I'll fix the last one.
